version: 0.1.10.{build}
branches:
  only:
  - master
image: Visual Studio 2017
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "Source\DotNetWorkQueue" -c Debug
  