version: 0.1.10.{build}
branches:
  only:
  - master
image: Visual Studio 2017
before_build:
- cmd: nuget restore Source\DotNetWorkQueue.sln
build:
  project: Source\DotNetWorkQueue.sln
  verbosity: minimal
  -test:
 -  assemblies: